CREATE TABLE USUARIOS (
    userId int IDENTITY(1, 1) NOT NULL,
    username varchar(255) NOT NULL,
    password varchar(255) NOT NULL,
    refreshtoken varchar(255) NULL,
    role CHAR (10) NOT NULL,
    PRIMARY KEY(userId)
);

CREATE TABLE OPE_MANAGERS (
    IDMANAGER int NOT NULL,
    NOMBRE varchar(255) NULL,
    ACTIVO int NULL,
    PRIMARY KEY (IDMANAGER),
    FOREIGN KEY (IDMANAGER) REFERENCES USUARIOS(userId)
)

CREATE TABLE OPE_RECOLECTORES (
    IDRECOLECTOR int NOT NULL,
    NOMBRE varchar(300) NULL,
    ID_ZONA int NULL,
    ID_TI_PORECOLECTOR INT NULL,
    IDZONA2 int NULL,
    ACTIVO int NULL,
    INDICE int NULL,
    PRIMARY KEY (IDRECOLECTOR),
    FOREIGN KEY (IDRECOLECTOR) REFERENCES USUARIOS(userId)
)


CREATE TABLE OPE_DONANTES (
    ID_DONANTE INT IDENTITY(1, 1) NOT NULL,
    A_PATERNO varchar(100) NOT NULL,
    A_MATERNO varchar(100) NULL,
    NOMBRE varchar(100) NOT NULL,
    FECHA_NAC date NULL,
    EMAIL varchar(50) NOT NULL,
    TEL_CASA INT NULL,
    TEL_OFICINA INT NULL,
    TEL_MOVIL INT NULL,
    ULTIMO_DONATIVO INT NULL,
    ID_GENERO INT NULL,
    PRIMARY KEY(ID_DONANTE)
)

CREATE TABLE COP_DONATIVOS_DONANTE (
    ID_DONATIVO INT IDENTITY(1, 1) NOT NULL,
    ID_DONANTE INT NOT NULL,
    ID_FORMA_PAGO INT NOT NULL,
    ID_FRECUENCIA INT NULL,
    NUM_FRECUENCIA INT NULL,
    ID_TIPO_FRECUENCIA INT NULL,
    PAGO_UNICO bit NULL,
    ID_ASIGNACION INT NULL,
    ID_CAMPANA_FINANCIERA INT NULL,
    ID_CATEGORIA INT NULL,
    IMPORTE float NULL,
    UID varchar(50) NULL,
    ID_ESTATUS INT NULL,
    PRIMARY KEY(ID_DONATIVO),
    FOREIGN KEY(ID_DONANTE) REFERENCES OPE_DONANTES(ID_DONANTE)   
)
  
CREATE TABLE OPE_BITACORA_PAGOS_DONATIVOS (
    ID_BITACORA INT IDENTITY(1, 1) NOT NULL,
    ID_DONATIVO INT NOT NULL,
    ID_NUM_PAGO INT NULL,
    ID_RECOLECTOR INT NULL,
    FECHA_COBRO date NULL,
    FECHA_PAGO date NULL,
    FECHA_VISITA date NULL,
    ID_FORMA_PAGO INT NULL,
    IMPORTE float NULL,
    ID_RECIBO varchar(50) NULL,
    ESTATUS_PAGO_TMP INT NULL,
    ESTATUS_PAGO INT NULL,
    COMENTARIOS varchar(MAX) NULL,
    ID_DIRECCION_COBRO INT NULL,
    USUARIO_CONFIRMACION varchar(50) NULL,
    FECHA_CONFIRMACION datetime NULL,
    USUARIO_CANCELACION varchar(50) NULL,
    USUARIO_PAGADO_INGRESOS varchar(50) NULL,
    FECHA_STATUS_PAGADO datetime NULL,
    FECHA_REPROGRAMACION datetime NULL,
    REPROGRAMACION_TELEFONISTA INT NULL DEFAULT ((0)),
    PRIMARY KEY(ID_BITACORA),
    FOREIGN KEY(ID_DONATIVO) REFERENCES COP_DONATIVOS_DONANTE(ID_DONATIVO),
    FOREIGN KEY(ID_RECOLECTOR) REFERENCES OPE_RECOLECTORES(IDRECOLECTOR)
  )
  
 -- USUARIOS
INSERT INTO USUARIOS (username, password, refreshtoken, role)
VALUES ('user1', '$2a$12$DsRB5Urc3dEGs3591XcEFes54zm9Jbi3PZz6fYaNTn3z2onG5lbe6', NULL, 'manager');

INSERT INTO USUARIOS (username, password, refreshtoken, role)
VALUES ('user2', '$2a$12$DsRB5Urc3dEGs3591XcEFes54zm9Jbi3PZz6fYaNTn3z2onG5lbe6', NULL, 'repartidor');

-- MANAGER

INSERT INTO OPE_MANAGERS (IDMANAGER, NOMBRE, ACTIVO)
VALUES (1, 'Manager 1', 1);

-- RECOLECTORES

INSERT INTO OPE_RECOLECTORES (IDRECOLECTOR, NOMBRE, ID_ZONA, ID_TI_PORECOLECTOR, IDZONA2, ACTIVO, INDICE)
VALUES (2, 'Recolector 2', 2, 2, 2, 1, 2);


-- DONANTES

INSERT INTO OPE_DONANTES (A_PATERNO, A_MATERNO, NOMBRE, FECHA_NAC, EMAIL, TEL_CASA, TEL_OFICINA, TEL_MOVIL, ULTIMO_DONATIVO, ID_GENERO)
VALUES ('Doe', 'Johnson', 'John', '1990-01-15', 'john@example.com', NULL, NULL, '55555555', 1, 1);

INSERT INTO OPE_DONANTES (A_PATERNO, A_MATERNO, NOMBRE, FECHA_NAC, EMAIL, TEL_CASA, TEL_OFICINA, TEL_MOVIL, ULTIMO_DONATIVO, ID_GENERO)
VALUES ('Smith', 'Williams', 'Emily', '1985-05-20', 'emily@example.com', '55555555', NULL, '55512345', 2, 2);

-- OPE_DONTIVOS

INSERT INTO COP_DONATIVOS_DONANTE (ID_DONANTE, ID_FORMA_PAGO, ID_FRECUENCIA, NUM_FRECUENCIA, ID_TIPO_FRECUENCIA, PAGO_UNICO, ID_ASIGNACION, ID_CAMPANA_FINANCIERA, ID_CATEGORIA, IMPORTE, UID, ID_ESTATUS)
VALUES (9, 1, 1, NULL, NULL, 0, 1, 1, 1, 100.00, 'UID123', 1);

INSERT INTO COP_DONATIVOS_DONANTE (ID_DONANTE, ID_FORMA_PAGO, ID_FRECUENCIA, NUM_FRECUENCIA, ID_TIPO_FRECUENCIA, PAGO_UNICO, ID_ASIGNACION, ID_CAMPANA_FINANCIERA, ID_CATEGORIA, IMPORTE, UID, ID_ESTATUS)
VALUES (10, 2, 2, 3, 1, 1, 2, 2, 2, 50.00, 'UID456', 2);

-- BITACORA

INSERT INTO OPE_BITACORA_PAGOS_DONATIVOS (ID_DONATIVO, ID_NUM_PAGO, ID_RECOLECTOR, FECHA_COBRO, FECHA_PAGO, FECHA_VISITA, ID_FORMA_PAGO, IMPORTE, ID_RECIBO, ESTATUS_PAGO_TMP, ESTATUS_PAGO, COMENTARIOS, ID_DIRECCION_COBRO, USUARIO_CONFIRMACION, FECHA_CONFIRMACION, FECHA_STATUS_PAGADO, FECHA_REPROGRAMACION, REPROGRAMACION_TELEFONISTA)
VALUES (4, 1, 2, '2023-09-06', '2023-09-06', '2023-09-06', 1, 100.00, 'REC123', 1, 2, 'Payment received', 1, 'admin', '2023-09-06 10:00:00', '2023-09-06 12:00:00', '2023-09-06 13:30:00', 0);




